In [200]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv
/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv
/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv

In [201]:
import pandas as pd

In [11]:
df = pd.read_csv("/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv")
df

      ID Prediction
0      1      A B C
1      2      A B C
2      3      A B C
3      4      A B C
4      5      A B C
..   ...        ...
495  496      A B C
496  497      A B C
497  498      A B C
498  499      A B C
499  500      A B C

[500 rows x 2 columns]

In [12]:
df.to_csv("submission.csv", index=False)

In [13]:
train = pd.read_csv("/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv")
train

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
1,2,What is accelerator-based light-ion fusion?,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,Accelerator-based light-ion fusion is a techni...,A
2,3,Determine the correct option: What is the term...,Blueshifting,Redshifting,Reddening,Whitening,Yellowing,C
3,4,Select the most accurate option: What is Marti...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B
4,5,Identify the correct statement: What is the co...,"Simultaneity is relative, meaning that two eve...","Simultaneity is relative, meaning that two eve...","Simultaneity is absolute, meaning that two eve...",Simultaneity is a concept that applies only to...,Simultaneity is a concept that applies only to...,A
...,...,...,...,...,...,...,...,...
1995,1996,What is the piezoelectric strain coefficient f...,d = 1.9·10‑12 m/V,d = 3.1·10‑12 m/V,d = 4.2·10‑12 m/V,d = 2.5·10‑12 m/V,d = 5.8·10‑12 m/V,B
1996,1997,Identify the correct statement: What is the sy...,A device used to demonstrate a neuro-inspired ...,A device used to demonstrate a neuro-inspired ...,A device used to demonstrate a neuro-inspired ...,A device used to demonstrate a neuro-inspired ...,A device used to demonstrate a neuro-inspired ...,E
1997,1998,Determine the correct option: What does Earnsh...,A collection of point charges can be maintaine...,A collection of point charges can be maintaine...,A collection of point charges can be maintaine...,A collection of point charges cannot be mainta...,A collection of point charges can be maintaine...,D
1998,1999,Identify the correct statement: What is the re...,The atmosphere is a mechanism that is only inf...,"The atmosphere possesses both chaos and order,...",The atmosphere is a structure that is only inf...,The atmosphere is a completely chaotic mechani...,The atmosphere is a completely ordered structu...,B
1999,2000,Pick the best possible answer: Which of the fo...,Gravitational waves have an amplitude denoted ...,Gravitational waves have an amplitude denoted ...,Gravitational waves have an amplitude denoted ...,Gravitational waves have an amplitude denoted ...,Gravitational waves have an amplitude denoted ...,C

In [14]:
test= pd.read_csv("/kaggle/input/competitions/smart-mcq-solver-challenge/test.csv")
test

,id,prompt,A,B,C,D,E
0,1,Pick the best possible answer: What is the rel...,"For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p...","For every eigenstate of one Hamiltonian, its p..."
1,2,"What is the estimated redshift of CEERS-93316,...","Approximately z = 6.0, corresponding to 1 bill...","Approximately z = 16.7, corresponding to 235.8...","Approximately z = 3.0, corresponding to 5 bill...","Approximately z = 10.0, corresponding to 13 bi...","Approximately z = 13.0, corresponding to 30 bi..."
2,3,Pick the best possible answer: What is the rea...,The sun appears yellowish due to a reflection ...,"The longer wavelengths of light, such as red a...",The sun appears yellowish due to the scatterin...,The sun emits a yellow light due to its own sp...,The atmosphere absorbs the shorter wavelengths...
3,4,What is the significance of the redshift-dista...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...,Observations of the redshift-distance relation...
4,5,What is the Landau-Lifshitz-Gilbert equation u...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...,The Landau-Lifshitz-Gilbert equation is a diff...
...,...,...,...,...,...,...,...
495,496,What are the constituents of cold dark matter?,"They are unknown, but possibilities include la...",They are known to be black holes and Preon stars.,They are only MACHOs.,They are clusters of brown dwarfs.,They are new particles such as RAMBOs.
496,497,Pick the best possible answer: What is a plane...,A framework of planets that are all located in...,A mechanism of planets that are all the same s...,Any set of gravitationally bound non-stellar o...,A mechanism of planets that are all located in...,A structure of planets that are all made of gas.
497,498,Pick the best possible answer: What is magneti...,Magnetic susceptibility is a measure of how mu...,Magnetic susceptibility is a measure of how mu...,Magnetic susceptibility is a measure of how mu...,Magnetic susceptibility is a measure of how mu...,Magnetic susceptibility is a measure of how mu...
498,499,Determine the correct option: What is the evid...,The Milky Way galaxy has a supermassive black ...,The Milky Way galaxy has a supermassive black ...,The Milky Way galaxy has a supermassive black ...,The Milky Way galaxy has a supermassive black ...,The star S2 follows an elliptical orbit with a...
499,500,What is the order parameter that breaks the el...,None of the above.,A thin cylindrical plastic rod.,A condensed-matter collective field ψ.,The cosmic microwave background.,A component of the Higgs field.

In [15]:
sample_sub = pd.read_csv("/kaggle/input/competitions/smart-mcq-solver-challenge/sample_submission.csv")
sample_sub

      ID Prediction
0      1      A B C
1      2      A B C
2      3      A B C
3      4      A B C
4      5      A B C
..   ...        ...
495  496      A B C
496  497      A B C
497  498      A B C
498  499      A B C
499  500      A B C

[500 rows x 2 columns]

In [16]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      2000 non-null   int64
 1   prompt  2000 non-null   object
 2   A       2000 non-null   object
 3   B       2000 non-null   object
 4   C       2000 non-null   object
 5   D       2000 non-null   object
 6   E       2000 non-null   object
 7   answer  2000 non-null   object
dtypes: int64(1), object(7)
memory usage: 125.1+ KB

In [17]:
train.head(1)

,id,prompt,A,B,C,D,E,answer
0,1,Pick the best possible answer: What is Martin ...,Martin Heidegger believes that humans exist wi...,Martin Heidegger believes that humans do not e...,Martin Heidegger does not believe in the exist...,Martin Heidegger believes that the relationshi...,Martin Heidegger believes that time is an illu...,B

In [18]:
train.shape

(2000, 8)

In [19]:
test.shape

(500, 7)

In [20]:
train.columns

Index(['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer'], dtype='object')

In [21]:
train.isna().sum()

id        0
prompt    0
A         0
B         0
C         0
D         0
E         0
answer    0
dtype: int64

In [22]:
Options = ["A", "B", "C", "D", "E"]
train[["prompt"] + Options].isna().sum().to_string()

'prompt    0\nA         0\nB         0\nC         0\nD         0\nE         0'

In [23]:
train[['prompt']+Options].isna().any(axis=1).sum()

np.int64(0)

In [24]:
test[["prompt"] + Options].isna().sum().to_string()

'prompt    0\nA         0\nB         0\nC         0\nD         0\nE         0'

In [25]:
test[['prompt']+Options].isna().any(axis=1).sum()

np.int64(0)

In [26]:
vc = train["answer"].value_counts()
vc

answer
B    490
C    459
A    369
D    358
E    324
Name: count, dtype: int64

In [27]:
vnc = train["answer"].value_counts(normalize=True).round(4)
vnc

answer
B    0.2450
C    0.2295
A    0.1845
D    0.1790
E    0.1620
Name: proportion, dtype: float64

In [28]:
train["answer"].value_counts().to_string()

'answer\nB    490\nC    459\nA    369\nD    358\nE    324'

In [29]:
train["answer"].value_counts(normalize=True).round(4).to_string()

'answer\nB    0.2450\nC    0.2295\nA    0.1845\nD    0.1790\nE    0.1620'

In [30]:
def apk(actual, pred, k=3):
    pred = pred[:k]
    return 1.0 / (pred.index(actual) + 1) if actual in pred else 0.0

In [31]:
def mapk(actuals, preds):
    return float(np.mean([apk(a, p) for a, p in zip(actuals, preds)]))

In [32]:
top3  = vc.index[:3].tolist()
top3

['B', 'C', 'A']

In [33]:
naive = mapk(train["answer"].tolist(), [top3] * len(train))
naive

0.42125

In [34]:
for c in ["prompt"] + Options:
    train[c] = train[c].fillna("").astype(str)
    test[c] = test[c].fillna("").astype(str)

when there is no missing values, then why this step??

In [35]:
plen = train["prompt"].str.split().apply(len)
olen = pd.concat([train[c].str.split().apply(len) for c in Options])

plen

0       22
1        5
2       27
3       19
4       15
        ..
1995    10
1996    16
1997    13
1998    37
1999    18
Name: prompt, Length: 2000, dtype: int64

In [36]:
olen

0       51
1       62
2        1
3       51
4       36
        ..
1995     4
1996    17
1997    22
1998    12
1999    59
Length: 10000, dtype: int64

In [37]:
plen.describe().round(1)

count    2000.0
mean       18.1
std         6.8
min         3.0
25%        14.0
50%        17.0
75%        22.0
max        51.0
Name: prompt, dtype: float64

In [38]:
print(f"95th pct : {plen.quantile(0.95):.0f} words")

95th pct : 31 words

In [39]:
olen.describe().round(1)

count    10000.0
mean        26.3
std         17.6
min          1.0
25%         13.0
50%         23.0
75%         36.0
max        118.0
dtype: float64

In [40]:
print(f"95th pct : {olen.quantile(0.95):.0f} words")

95th pct : 61 words

In [41]:
p95 = int(plen.quantile(0.95))
o95 = int(olen.quantile(0.95))

In [42]:
print(f"\nSafe tokenizer max_length estimate : {p95 + o95} words -> ~{(p95+o95)*2} BPE tokens")

Safe tokenizer max_length estimate : 92 words -> ~184 BPE tokens

In [43]:
PREFIX_PATTERNS = [
    r"^pick the best possible answer:?\s*",
    r"^select the most accurate option:?\s*",
    r"^determine the correct option:?\s*",
    r"^identify the correct statement:?\s*",
    r"^which of the following is correct\??\s*",
    r"^choose the correct answer:?\s*",
]

In [44]:
SUFFIX_PATTERNS = [
    r"\s*carefully\.?$",
    r"\s*based on the given context\.?$",
    r"\s*from the following choices\.?$",
    r"\s*among the listed options\.?$",
]

Why we have used above pattern? how did we find that? we haven't shown that why or the thought process of that?

In [45]:
import re

In [46]:
def strip_wrapper(t: str) -> str:
    t = t.lower().strip()
    for p in PREFIX_PATTERNS: t = re.sub(p, "", t)
    for p in SUFFIX_PATTERNS: t = re.sub(p, "", t)
    t = re.sub(r"[^a-z0-9\s]", " ", t)
    return re.sub(r"\s+", " ", t).strip()

In [47]:
train["core"] = train["prompt"].apply(strip_wrapper)
test["core"] = test["prompt"].apply(strip_wrapper)
train["core"]

0       what is martin heidegger s view on the relatio...
1              what is accelerator based light ion fusion
2       what is the term used in astrophysics to descr...
3       what is martin heidegger s view on the relatio...
4       what is the concept of simultaneity in einstei...
                              ...
1995    what is the piezoelectric strain coefficient f...
1996          what is the synapstor or synapse transistor
1997                   what does earnshaw s theorem state
1998    what is the revised view of the atmosphere s n...
1999    which of the following statements accurately d...
Name: core, Length: 2000, dtype: object

In [48]:
train["group"] = train["core"].astype("category").cat.codes
train["group"]

0        51
1        39
2       202
3        51
4        72
       ...
1995    142
1996    201
1997     16
1998    179
1999    231
Name: group, Length: 2000, dtype: int16

In [49]:
dup = train["core"].value_counts()
dup

core
what is the definition of an improper rotation                                                                                                                                21
what is the significance of the high degree of fatty acyl disorder in the thylakoid membranes of plants                                                                       20
what was the aim of the gravity probe b gp b mission                                                                                                                          18
what is the gravitomagnetic interaction                                                                                                                                       18
which of the following statements accurately describes the impact of modified newtonian dynamics mond on the observed missing baryonic mass discrepancy in galaxy clusters    16
                                                                                                                                                                              ..
who published the first framework that was able to encompass previously separate field theories to provide a unifying framework of electromagnetism                            1
what is a planetary system                                                                                                                                                     1
who published the first theory that was able to encompass previously separate field theories to provide a unifying theory of electromagnetism                                  1
which mathematical function is commonly used to characterize linear time invariant structures                                                                                  1
which mathematical function is commonly used to characterize linear time invariant systems                                                                                     1
Name: count, Length: 252, dtype: int64

In [50]:
print(f"Total train rows : {len(train)}")
print(f"Unique core questions : {dup.shape[0]}")
print(f"Avg copies per question : {len(train)/dup.shape[0]:.1f}x")
print(f"Clusters with >1 copy : {(dup>1).sum()}")
print(f"Rows inside duplicate clusters: {dup[dup>1].sum()}")
print(f"\nTop 10 largest duplicate clusters:")
print(dup.head(10).to_string())

Total train rows : 2000
Unique core questions : 252
Avg copies per question : 7.9x
Clusters with >1 copy : 222
Rows inside duplicate clusters: 1970

Top 10 largest duplicate clusters:
core
what is the definition of an improper rotation                                                                                                                                21
what is the significance of the high degree of fatty acyl disorder in the thylakoid membranes of plants                                                                       20
what was the aim of the gravity probe b gp b mission                                                                                                                          18
what is the gravitomagnetic interaction                                                                                                                                       18
which of the following statements accurately describes the impact of modified newtonian dynamics mond on the observed missing baryonic mass discrepancy in galaxy clusters    16
what is a trophic level in an ecological pyramid                                                                                                                              16
what are permutation inversion groups                                                                                                                                         16
what was pierre de fermat s solution to the problem of refraction                                                                                                             16
how many crystallographic point groups are there in three dimensional space                                                                                                   16
what is the maxwell s demon thought experiment                                                                                                                                16

In [51]:
# Are all copies of the same question labeled with the same answer?
consistent = train.groupby("core")["answer"].apply(lambda s: s.nunique() == 1)
print(f"\nClusters with 100% consistent answer: {consistent.sum()}/{len(consistent)} ({consistent.mean():.1%})")

Clusters with 100% consistent answer: 252/252 (100.0%)

In [52]:
dup_test = test["core"].value_counts()
overlap = set(train["core"]) & set(test["core"])
overlap

{'how do the lunar laser ranging experiment radar astronomy and the deep space network determine distances to the moon planets and spacecraft',
 'how many crystallographic point groups are there in three dimensional space',
 'what are amorphous ferromagnetic metallic alloys and what are their advantages',
 'what are coherent turbulent structures',
 'what are permutation inversion groups',
 'what are some models that attempt to account for all observations without invoking supplemental non baryonic matter',
 'what are the constituents of cold dark matter',
 'what are the four qualitative levels of crystallinity described by geologists',
 'what are the navier stokes equations',
 'what are the two main factors that cause resistance in a metal',
 'what are the two main interpretations for the disparity between the presence of matter and antimatter in the observable universe',
 'what can be inferred about the electronic entropy of insulators and metals based on their densities of states at the fermi level',
 'what did arthur eddington discover about two of einstein s types of gravitational waves',
 'what did fresnel predict and verify with regards to total internal reflections',
 'what did newton adopt after his correspondence with hooke in 1679 1680',
 'what did newton s manuscripts of the 1660s show',
 'what does earnshaw s theorem state',
 'what happens to an initially inhomogeneous physical framework that is isolated by a thermodynamic operation',
 'what happens to an initially inhomogeneous physical mechanism that is isolated by a thermodynamic operation',
 'what happens to an initially inhomogeneous physical system that is isolated by a thermodynamic operation',
 'what happens to excess base metal as a solution cools from the upper transformation temperature towards an insoluble state',
 'what is a coffee ring in physics',
 'what is a crossover experiment',
 'what is a hilbert space in quantum mechanics',
 'what is a light year',
 'what is a magnetic monopole in particle physics',
 'what is a phageome',
 'what is a planetary framework',
 'what is a planetary mechanism',
 'what is a planetary structure',
 'what is a planetary system',
 'what is a pycnometer',
 'what is a regular polytope',
 'what is a schwarzschild black hole',
 'what is a transient condensation cloud also known as a wilson cloud',
 'what is a trophic level in an ecological pyramid',
 'what is a uniform tiling in the hyperbolic plane',
 'what is a virtual particle',
 'what is accelerator based light ion fusion',
 'what is an order parameter',
 'what is bollard pull primarily used for measuring',
 'what is classical mechanics',
 'what is emissivity',
 'what is explicit symmetry breaking in theoretical physics',
 'what is geometric quantization in mathematical physics',
 'what is hesse s principle of transfer in geometry',
 'what is indirect photophoresis',
 'what is linear frame dragging',
 'what is lorentz symmetry or lorentz invariance in relativistic physics',
 'what is magnetic susceptibility',
 'what is martin heidegger s view on the relationship between time and human existence',
 'what is minkowski space',
 'what is modified newtonian dynamics mond',
 'what is one of the examples of the models proposed by cosmologists and theoretical physicists without the cosmological or copernican principles that can be used to address specific issues in the lambda cdm model and distinguish between current models and other possible models',
 'what is organography',
 'what is power density in the context of energy frameworks and how does it differ between renewable and non renewable energy sources',
 'what is power density in the context of energy systems and how does it differ between renewable and non renewable energy sources',
 'what is radiometric dating',
 'what is radiosity in radiometry',
 'what is reciprocal length or inverse length',
 'what is resistivity',
 'what is spatial dispersion',
 'what is spontaneous symmetry breaking',
 'what is the american petroleum institute api gravity',
 'what is the application of memristor',
 'what is the butterfly effect',
 'what is the butterfly effect as defined by lorenz in his book the essence of chaos',
 'what is the carnot engine',
 'what is the cause of the observed change in the periods of moons orbiting a distant planet when measured from earth',
 'what is the concept of simultaneity in einstein s book relativity',
 'what is the contrast between active and passive transport in cells',
 'what is the contrast between natural convection and forced convection',
 'what is the contrast between redshift due to the expansion of the universe and doppler redshift',
 'what is the contrast between the coevolution of myrmecophytes and the mutualistic symbiosis of mycorrhiza',
 'what is the de haas van alphen effect',
 'what is the decay energy for the free neutron decay process',
 'what is the definition of an improper rotation',
 'what is the definition of anatomy',
 'what is the definition of atomristor',
 'what is the definition of dimension in mathematics',
 'what is the difference between active and passive transport in cells',
 'what is the difference between illuminance and luminance',
 'what is the difference between natural convection and forced convection',
 'what is the difference between probability mass function pmf and probability density function pdf',
 'what is the difference between redshift due to the expansion of the universe and doppler redshift',
 'what is the difference between the coevolution of myrmecophytes and the mutualistic symbiosis of mycorrhiza',
 'what is the distinction between illuminance and luminance',
 'what is the distinction between probability mass function pmf and probability density function pdf',
 'what is the droste effect',
 'what is the effect generated by a spinning superconductor',
 'what is the einstein home project',
 'what is the erlangen program',
 'what is the estimated redshift of ceers 93316 a candidate high redshift galaxy observed by the james webb space telescope',
 'what is the evans balance',
 'what is the evidence for the existence of a supermassive black hole at the center of the milky way galaxy',
 'what is the explanation for the effective supersymmetry in quark diquark models',
 'what is the fate of a carbocation formed in crystalline naphthalene',
 'what is the formalism that angular momentum is associated with in rotational invariance',
 'what is the function of mammary glands in mammals',
 'what is the function of the fibrous cardiac skeleton',
 'what is the gravitomagnetic interaction',
 'what is the heisenberg uncertainty principle and how does it relate to angular momentum in quantum mechanics',
 'what is the identity operation in symmetry groups',
 'what is the information loss paradox in black holes',
 'what is the interpretation of supersymmetry in stochastic supersymmetric theory',
 'what is the interstellar medium ism',
 'what is the isophotal diameter used for in measuring a galaxy s size',
 'what is the josephson effect',
 'what is the kelvin helmholtz instability and how does it affect earth s magnetosphere',
 'what is the kutta condition',
 'what is the landau lifshitz gilbert equation used for in physics',
 'what is the liouville density',
 'what is the main advantage of ferroelectric memristors',
 'what is the main factor that determines the occurrence of each type of supernova',
 'what is the main focus of cryogenic and noble liquid detectors in dark matter experiments',
 'what is the main focus of the environmental science center at qatar university',
 'what is the main sequence in astronomy',
 'what is the maxwell s demon thought experiment',
 'what is the meaning of the term horror vacui',
 'what is the mechanism of ftir',
 'what is the metallicity of kapteyn s star estimated to be',
 'what is the minkowski diagram used for',
 'what is the most popular explanation for the shower curtain effect',
 'what is the optical signal to noise ratio osnr',
 'what is the order parameter that breaks the electromagnetic gauge symmetry in superconductors',
 'what is the origin of the permanent moment in paramagnetism',
 'what is the origin of the radio emission observed from supernova remnants',
 'what is the ozma problem',
 'what is the peierls bracket in canonical quantization',
 'what is the penrose process',
 'what is the piezoelectric strain coefficient for at cut quartz crystals',
 'what is the propagation constant in sinusoidal waves',
 'what is the proper distance for a redshift of 8 2',
 'what is the proposed name for the field that is responsible for cosmic inflation and the metric expansion of space',
 'what is the purpose of expressing a map s scale as a ratio such as 1 10 000',
 'what is the purpose of measuring the larmor precession fields at about 100 microtesla with highly sensitive superconducting quantum interference devices squids in ultra low field mri',
 'what is the purpose of obtaining surgical resection specimens',
 'what is the purpose of the proximity focusing design in a rich detector',
 'what is the ramsauer townsend effect',
 'what is the reactive leidenfrost effect observed in non volatile materials',
 'what is the reason behind the adoption of a logarithmic scale of 5 100 2 512 between magnitudes in astronomy',
 'what is the reason behind the designation of class l dwarfs and what is their color and composition',
 'what is the reason behind the largest externally observed electrical effects when two conductors are separated by the smallest distance without touching',
 'what is the reason for heating metals to a temperature just above the upper critical temperature',
 'what is the reason for recycling rare metals according to the united nations',
 'what is the reason for the formation of stars exclusively within molecular clouds',
 'what is the reason for the stochastic nature of all observed resistance switching processes',
 'what is the reason for the sun appearing slightly yellowish when viewed from earth',
 'what is the reason that it is nearly impossible to see light emitted at the lyman alpha transition wavelength from a star farther than a few hundred light years from earth',
 'what is the reason that newton s second law cannot be used to calculate the development of a physical framework in quantum mechanics',
 'what is the reason that newton s second law cannot be used to calculate the development of a physical system in quantum mechanics',
 'what is the relation between the three moment theorem and the bending moments at three successive supports of a continuous beam',
 'what is the relationship between chemical potential and quarks antiquarks',
 'what is the relationship between coordinated universal time utc and universal time ut1',
 'what is the relationship between dielectric loss and the transparency of a material',
 'what is the relationship between interstellar and cometary chemistry',
 'what is the relationship between mass force and acceleration according to sir isaac newton s laws of motion',
 'what is the relationship between the amplitude of a sound wave and its loudness',
 'what is the relationship between the cauchy momentum equation and the navier stokes equation',
 'what is the relationship between the complete electromagnetic hamiltonian of a molecule and the parity operation',
 'what is the relationship between the hamiltonians and eigenstates in supersymmetric quantum mechanics',
 'what is the relationship between the wigner function and the density matrix operator',
 'what is the relevant type of coherence for the young s double slit interferometer',
 'what is the required excess quark per billion quark antiquark pairs in the early universe in order to provide all the observed matter in the universe',
 'what is the result of the collapse of a cavitation bubble',
 'what is the revised view of the atmosphere s nature based on the time varying multistability that is associated with the modulation of large scale processes and aggregated feedback of small scale processes',
 'what is the roche limit',
 'what is the role of axioms in a formal concept',
 'what is the role of axioms in a formal theory',
 'what is the role of cycloidea genes in the evolution of bilateral symmetry',
 'what is the role of il 10 in the formation of tr1 cells and tolerogenic dcs',
 'what is the role of methane in fischer tropsch processes',
 'what is the role of the higgs boson in the standard model',
 'what is the second law of thermodynamics',
 'what is the si base unit of time and how is it defined',
 'what is the si unit of the physical quantity m q',
 'what is the significance of baryon acoustic oscillations baos in the study of the universe',
 'what is the significance of probability amplitudes in quantum mechanics',
 'what is the significance of regularization in terms of renormalization problems in physics',
 'what is the significance of the change in slope of the pinched hysteresis curves in reram and other forms of two terminal resistance memory',
 'what is the significance of the discovery of the crab pulsar',
 'what is the significance of the high degree of fatty acyl disorder in the thylakoid membranes of plants',
 'what is the significance of the redshift distance relationship in determining the expansion history of the universe',
 'what is the significance of the speed of light in vacuum',
 'what is the spin quantum number',
 'what is the synapstor or synapse transistor',
 'what is the term used in astrophysics to describe light matter interactions resulting in energy shifts in the radiation field',
 'what is the term used to describe the conduction that occurs in non crystalline semiconductors by charges quantum tunnelling from one localised site to another',
 'what is the term used to describe the proportionality factor to the stefan boltzmann law that is utilized in subsequent evaluations of the radiative behavior of grey bodies',
 'what is the throttling process and why is it essential',
 'what is the throttling process and why is it important',
 'what is the ultraviolet catastrophe',
 'what is the variation between active and passive transport in cells',
 'what is the variation between natural convection and forced convection',
 'what is the variation between redshift due to the expansion of the universe and doppler redshift',
 'what is the variation between the coevolution of myrmecophytes and the mutualistic symbiosis of mycorrhiza',
 'what is water hammer',
 'what is x ray pulsar based navigation xnav',
 'what was isaac newton s explanation for rectilinear propagation of light',
 'what was pierre de fermat s solution to the problem of refraction',
 'what was the aim of the gravity probe b gp b mission',
 'which hand should be used to apply the right hand rule when tightening or loosening nuts screws bolts bottle caps and jar lids',
 'which mathematical function is commonly used to characterize linear time invariant frameworks',
 'which mathematical function is commonly used to characterize linear time invariant structures',
 'which mathematical function is commonly used to characterize linear time invariant systems',
 'which of the following is an accurate definition of dynamic scaling in self similar frameworks',
 'which of the following is an accurate definition of dynamic scaling in self similar structures',
 'which of the following is an accurate definition of dynamic scaling in self similar systems',
 'which of the following statements accurately depicts the relationship between gauss s law electric flux electric field and symmetry in electric fields',
 'which of the following statements accurately describes the blocking temperature of an antiferromagnetic layer in a spin valve',
 'which of the following statements accurately describes the characteristics of gravitational waves',
 'which of the following statements accurately describes the dimension of an object in a cw complex',
 'which of the following statements accurately describes the impact of modified newtonian dynamics mond on the observed missing baryonic mass discrepancy in galaxy clusters',
 'which of the following statements accurately describes the origin and significance of the triskeles symbol',
 'which of the following statements accurately describes the relationship between the dimensions of a diffracting object and the angular spacing of features in the diffraction pattern',
 'which of the following statements is true about the categorization of planetary frameworks according to their orbital dynamics',
 'which of the following statements is true about the categorization of planetary mechanisms according to their orbital dynamics',
 'which of the following statements is true about the categorization of planetary structures according to their orbital dynamics',
 'which of the following statements is true about the categorization of planetary systems according to their orbital dynamics',
 'who proposed the concept of maximal acceleration',
 'who proposed the principle of complexity from noise and when was it first introduced',
 'who published the first framework that was able to encompass previously separate field theories to provide a unifying framework of electromagnetism',
 'who published the first theory that was able to encompass previously separate field theories to provide a unifying theory of electromagnetism',
 'who shared the other half of the nobel prize with yoichiro nambu for discovering the origin of the explicit breaking of cp symmetry in the weak interactions',
 'who was giordano bruno',
 'who was the first person to describe the pulmonary circulation mechanism',
 'who was the first person to describe the pulmonary circulation system',
 'who was the first to determine the velocity of a star moving away from the earth using the doppler effect'}

In [53]:
print(f"Unique core questions in test : {dup_test.shape[0]}")
print(f"Of those, already seen in train (exact) : {len(overlap)} ({len(overlap)/dup_test.shape[0]:.1%})")
print(f"Test rows with a direct retrieval match : {test['core'].isin(set(train['core'])).sum()} / {len(test)}")
print(f"Duplicate clusters inside test : {(dup_test>1).sum()}")

Unique core questions in test : 228
Of those, already seen in train (exact) : 228 (100.0%)
Test rows with a direct retrieval match : 500 / 500
Duplicate clusters inside test : 153

In [54]:
print(f"\nFirst 5 overlapping core questions:")
for q in list(overlap)[:5]:
    print(f" -> {q[:100]}")

First 5 overlapping core questions:
 -> what is the landau lifshitz gilbert equation used for in physics
 -> which of the following statements is true about the categorization of planetary structures according
 -> what are the two main factors that cause resistance in a metal
 -> what is the reason that newton s second law cannot be used to calculate the development of a physica
 -> what is the si unit of the physical quantity m q

In [55]:
from itertools import combinations

In [56]:
def jaccard(a: set, b: set) -> float:
    return len(a & b) / len(a | b) if (a | b) else 0.0

In [57]:
def tok_set(t: str) -> set:
    return set(re.findall(r"[a-z0-9]+", t.lower()))

In [58]:
avg_overlap_list = []
margin_list = []

In [59]:
for _, row in train.iterrows():
    opt_sets = {c: tok_set(row[c]) for c in Options}
    pairs = list(combinations(Options, 2))
    avg_overlap_list.append(np.mean([jaccard(opt_sets[a], opt_sets[b]) for a, b in pairs]))

    pset = tok_set(row["prompt"])
    correct = row["answer"]
    c_ov = jaccard(pset, opt_sets[correct])
    i_ov = np.mean([jaccard(pset, opt_sets[c]) for c in Options if c != correct])
    margin_list.append(c_ov - i_ov)

In [60]:
avg_overlap_s = pd.Series(avg_overlap_list)
margin_s = pd.Series(margin_list)
avg_overlap_s

0       0.306770
1       0.760694
2       0.000000
3       0.306770
4       0.451501
          ...
1995    0.613889
1996    0.846537
1997    0.814206
1998    0.240302
1999    0.940000
Length: 2000, dtype: float64

In [61]:
margin_s

0      -0.057184
1      -0.007469
2       0.000000
3      -0.061263
4      -0.007368
          ...
1995    0.000000
1996    0.000000
1997    0.000980
1998   -0.033425
1999    0.000000
Length: 2000, dtype: float64

In [62]:
print(avg_overlap_s.describe().round(3).to_string())
print(f"\nQuestions where options are >50% similar: {(avg_overlap_s > 0.5).mean():.1%}")

count    2000.000
mean        0.516
std         0.267
min         0.000
25%         0.300
50%         0.535
75%         0.764
max         0.940

Questions where options are >50% similar: 53.1%

In [63]:
print(margin_s.describe().round(4).to_string())
print(f"\nCorrect option is NOT the most lexically similar to prompt: {(margin_s <= 0).mean():.1%}")

count    2000.0000
mean       -0.0117
std         0.0352
min        -0.1612
25%        -0.0247
50%        -0.0040
75%         0.0010
max         0.1597

Correct option is NOT the most lexically similar to prompt: 73.7%

## Q1-Milestone1
**Calculate the frequency distribution of the correct  answer  (A, B, C, D, E) in train.csv. Based on your counts, what is the sum of the occurrences of the most frequent option and the least frequent option?**

In [64]:
train['answer'].value_counts().sort_index()

answer
A    369
B    490
C    459
D    358
E    324
Name: count, dtype: int64

In [65]:
freq = train['answer'].value_counts().sort_index()
freq

answer
A    369
B    490
C    459
D    358
E    324
Name: count, dtype: int64

In [66]:
freq.min(), freq.max()

(324, 490)

In [67]:
mn = freq.min()
mx = freq.max()
sum = mn+mx
sum

814

## Q2

**After converting the prompt column to lowercase and removing all standard punctuation characters (using Python's string.punctuation), split the text by whitespace. What is the total number of unique words (vocabulary size) across the entire cleaned prompt column of train.csv?**  
*

In [68]:
import string

In [69]:
clean_prompts = (train["prompt"].str.lower().str.translate(str.maketrans('', '', string.punctuation)))

clean_prompts

0       pick the best possible answer what is martin h...
1                what is acceleratorbased lightion fusion
2       determine the correct option what is the term ...
3       select the most accurate option what is martin...
4       identify the correct statement what is the con...
                              ...
1995    what is the piezoelectric strain coefficient f...
1996    identify the correct statement what is the syn...
1997    determine the correct option what does earnsha...
1998    identify the correct statement what is the rev...
1999    pick the best possible answer which of the fol...
Name: prompt, Length: 2000, dtype: object

In [70]:
vocab = set()

In [71]:
for text in clean_prompts:
    vocab.update(text.split())

In [72]:
len(vocab)

859

In [73]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [74]:
row1 = train[train["id"] == 1].iloc[0]

In [75]:
prompt = (row1["prompt"].lower().translate(str.maketrans('', '', string.punctuation)))
prompt

'pick the best possible answer what is martin heideggers view on the relationship between time and human existence among the listed options'

In [76]:
words = prompt.split()

filtered_words = [
    word for word in words
    if word not in ENGLISH_STOP_WORDS
]
filtered_words

['pick',
 'best',
 'possible',
 'answer',
 'martin',
 'heideggers',
 'view',
 'relationship',
 'time',
 'human',
 'existence',
 'listed',
 'options']

In [77]:
len(filtered_words)

13

In [78]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [79]:
combined_text = (
    train["prompt"] + " " +
    train["A"] + " " +
    train["B"] + " " +
    train["C"] + " " +
    train["D"] + " " +
    train["E"]
)
combined_text

0       Pick the best possible answer: What is Martin ...
1       What is accelerator-based light-ion fusion? Ac...
2       Determine the correct option: What is the term...
3       Select the most accurate option: What is Marti...
4       Identify the correct statement: What is the co...
                              ...
1995    What is the piezoelectric strain coefficient f...
1996    Identify the correct statement: What is the sy...
1997    Determine the correct option: What does Earnsh...
1998    Identify the correct statement: What is the re...
1999    Pick the best possible answer: Which of the fo...
Length: 2000, dtype: object

In [80]:
vectorizer = TfidfVectorizer(stop_words="english")

In [81]:
X = vectorizer.fit_transform(combined_text)
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 64180 stored elements and shape (2000, 2762)>

In [82]:
X.shape

(2000, 2762)

In [83]:
from sklearn.metrics.pairwise import cosine_similarity

In [84]:
row1 = train[train["id"] == 1].iloc[0]

In [85]:

prompt_vec = vectorizer.transform([row1["prompt"]])

optionA_vec = vectorizer.transform([row1["A"]])

similarity = cosine_similarity(prompt_vec,optionA_vec)[0][0]

similarity

np.float64(0.27202429519891635)

In [86]:
round(similarity, 4)

np.float64(0.272)

In [87]:
options = ["A","B","C","D","E"]
correct = 0

In [88]:
for _, row in train.iterrows():

    prompt_vec = vectorizer.transform([row["prompt"]])

    scores = {}

    for option in options:

        option_vec = vectorizer.transform([row[option]])

        scores[option] = cosine_similarity(prompt_vec,option_vec)[0][0]

    prediction = max(
        scores,
        key=scores.get
    )

    if prediction == row["answer"]:
        correct += 1

accuracy = (correct / len(train)) * 100

accuracy

13.55

In [89]:
def map3(actual, preds):

    for rank, pred in enumerate(preds[:3], start=1):

        if pred == actual:
            return 1 / rank

    return 0

In [90]:
freq = train["answer"].value_counts()

top3 = freq.index[:3].tolist()

top3

['B', 'C', 'A']

In [91]:
scores = []

for actual in train["answer"]:

    scores.append(
        map3(actual, top3)
    )
np.mean(scores)

np.float64(0.42125)

In [92]:
def map3(actual, preds):

    for rank, pred in enumerate(preds[:3], start=1):

        if pred == actual:
            return 1 / rank

    return 0

In [93]:
options = ["A","B","C","D","E"]

In [94]:
scores = []

In [95]:
for _, row in train.iterrows():

    prompt_vec = vectorizer.transform([row["prompt"]])

    similarities = {}

    for option in options:

        option_vec = vectorizer.transform([row[option]])

        similarities[option] = cosine_similarity(prompt_vec,option_vec)[0][0]

    ranked_options = sorted(
        similarities,
        key=similarities.get,
        reverse=True
    )

    top3 = ranked_options[:3]

    scores.append(
        map3(row["answer"],top3)
    )

In [96]:
np.mean(scores)

np.float64(0.2961666666666667)

## Milestone 2

In [202]:
!pip -q install transformers datasets sentence-transformers accelerate

In [203]:
from datasets import load_dataset

In [204]:
from transformers import (AutoTokenizer,AutoModel,pipeline)

In [205]:
from sentence_transformers import SentenceTransformer, util

In [206]:
import torch

In [207]:
dataset = load_dataset(
    "csv",
    data_files="/kaggle/input/competitions/smart-mcq-solver-challenge/train.csv"
)

tr = dataset["train"]

tr

Dataset({
    features: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer'],
    num_rows: 2000
})

In [208]:
tr = tr.map(
    lambda x: {
        "combined_text":
        x["prompt"] + " " + x["A"]
    }
)

In [209]:
tr[51]

{'id': 52,
 'prompt': 'Determine the correct option: What is the reason behind the designation of Class L dwarfs, and what is their color and composition? among the listed options.',
 'A': 'Class L dwarfs are hotter than M stars and are designated L because L is the remaining letter alphabetically closest to M. They are bright blue in color and are brightest in ultraviolet. Their atmosphere is hot enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses large enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.',
 'B': 'Class L dwarfs are cooler than M stars and are designated L because L is the remaining letter alphabetically closest to M. They are dark red in color and are brightest in infrared. Their atmosphere is cool enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses large enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.',
 'C': 'Class L dwarfs are hotter than M stars and are designated L because L is the next letter alphabetically after M. They are dark red in color and are brightest in infrared. Their atmosphere is cool enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses large enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.',
 'D': 'Class L dwarfs are cooler than M stars and are designated L because L is the next letter alphabetically after M. They are bright yellow in color and are brightest in visible light. Their atmosphere is hot enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses large enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.',
 'E': 'Class L dwarfs are cooler than M stars and are designated L because L is the remaining letter alphabetically closest to M. They are bright green in color and are brightest in visible light. Their atmosphere is cool enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses small enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.',
 'answer': 'B',
 'combined_text': 'Determine the correct option: What is the reason behind the designation of Class L dwarfs, and what is their color and composition? among the listed options. Class L dwarfs are hotter than M stars and are designated L because L is the remaining letter alphabetically closest to M. They are bright blue in color and are brightest in ultraviolet. Their atmosphere is hot enough to allow metal hydrides and alkali metals to be prominent in their spectra. Some of these objects have masses large enough to support hydrogen fusion and are therefore stars, but most are of substellar mass and are therefore brown dwarfs.'}

In [210]:
combined_text

0       Pick the best possible answer: What is Martin ...
1       What is accelerator-based light-ion fusion? Ac...
2       Determine the correct option: What is the term...
3       Select the most accurate option: What is Marti...
4       Identify the correct statement: What is the co...
                              ...
1995    What is the piezoelectric strain coefficient f...
1996    Identify the correct statement: What is the sy...
1997    Determine the correct option: What does Earnsh...
1998    Identify the correct statement: What is the re...
1999    Pick the best possible answer: Which of the fo...
Length: 2000, dtype: object

#### Q1
Load train.csv using the Hugging Face datasets library (do not use pandas). Use the .map() function to create a new column called combined_text that concatenates the prompt and A columns with a space in between. E.g., prompt_text A_text. What is the exact character length (total number of string characters using Python's len() function, NOT the number of tokens) of the combined_text string for the row at index 51? Note: We follow zero-indexing here

In [211]:
len(tr[51]["combined_text"])

614

#### Q2

In [212]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [213]:
tokenizer.vocab_size

30522

#### Q3

In [214]:
tokenizer.sep_token_id

102

#### Q4

In [216]:
encoding = tokenizer(
    list(tr["prompt"]),
    padding="max_length",
    truncation=True,
    max_length=128,
    return_tensors="pt"
)

print(encoding["input_ids"].shape)

torch.Size([2000, 128])

In [217]:
def tokenize_function(example):
    return tokenizer(
        example["prompt"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

tokenized_dataset = tr.map(tokenize_function)

tokenized_dataset

Dataset({
    features: ['id', 'prompt', 'A', 'B', 'C', 'D', 'E', 'answer', 'combined_text', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2000
})

#### Q6

In [220]:
from transformers import AutoModel

model = AutoModel.from_pretrained(
    "bert-base-uncased"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [222]:
text = tr[0]["prompt"]

inputs = tokenizer(
    text,
    return_tensors="pt"
)

In [223]:
outputs = model(**inputs)
#outputs

In [224]:
outputs.last_hidden_state.shape

torch.Size([1, 31, 768])

#### Q7

In [225]:
index = 0
cls = outputs.last_hidden_state[0,0]
cls[:5]

tensor([-0.4677, -0.0754, -0.2019, -0.0071, -0.4480], grad_fn=<SliceBackward0>)

In [226]:
round(
    cls[:5].sum().item(),
    4
)

-1.2001

#### Q8

In [227]:
from transformers import AutoModel

model = AutoModel.from_pretrained(
    "bert-base-uncased",
    output_attentions=True
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [229]:
text = "Light-ion fusion is a technique."

inputs = tokenizer(
    text,
    return_tensors="pt"
)

In [230]:
tokens = tokenizer.convert_ids_to_tokens(
    inputs["input_ids"][0]
)

print(tokens)

['[CLS]', 'light', '-', 'ion', 'fusion', 'is', 'a', 'technique', '.', '[SEP]']

In [231]:
fusion_index = tokens.index("fusion")

print(fusion_index)

4

In [232]:
outputs = model(**inputs)

In [233]:
print(outputs.attentions[-1].shape)

torch.Size([1, 12, 10, 10])

In [234]:
last_layer = outputs.attentions[-1]

head0 = last_layer[0, 0]

In [235]:
attention = head0[0, fusion_index]

print(attention)
print(round(attention.item(), 4))

tensor(0.1025, grad_fn=<SelectBackward0>)
0.1025

In [237]:
print(tokens)

print(fusion_index)

print(round(attention.item(), 4))

['[CLS]', 'light', '-', 'ion', 'fusion', 'is', 'a', 'technique', '.', '[SEP]']
4
0.1025

#### Q9

In [238]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

prompt = tr[0]["prompt"]
optionB = tr[0]["B"]

prompt_embedding = model.encode(
    prompt,
    convert_to_tensor=True
)

optionB_embedding = model.encode(
    optionB,
    convert_to_tensor=True
)

similarity = util.cos_sim(
    prompt_embedding,
    optionB_embedding
)

print(similarity)
print(round(similarity.item(), 4))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tensor([[0.7658]])
0.7658

#### Q10

In [239]:
from sentence_transformers import SentenceTransformer, util

st_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [240]:
tfidf_top3 = []

In [241]:
minilm_top3 = []

In [175]:
#MAP@3

NameError: name 'MAP' is not defined

In [242]:
def map3(actual, preds):
    for rank, pred in enumerate(preds[:3], start=1):
        if pred == actual:
            return 1 / rank
    return 0

In [243]:
options = ["A", "B", "C", "D", "E"]

In [244]:
tfidf_predictions = []
minilm_predictions = []

minilm_scores = []

improved_count = 0

In [245]:
from sklearn.metrics.pairwise import cosine_similarity

for _, row in train.iterrows():

    #  TF-IDF 

    prompt_vec = vectorizer.transform([row["prompt"]])

    tfidf_scores = {}

    for op in options:

        option_vec = vectorizer.transform([row[op]])

        tfidf_scores[op] = cosine_similarity(
            prompt_vec,
            option_vec
        )[0][0]

    tfidf_top3 = sorted(
        tfidf_scores,
        key=tfidf_scores.get,
        reverse=True
    )[:3]

    tfidf_predictions.append(tfidf_top3)

    # - MiniLM 

    texts = [
        row["prompt"],
        row["A"],
        row["B"],
        row["C"],
        row["D"],
        row["E"]
    ]

    embeddings = st_model.encode(
        texts,
        convert_to_tensor=True
    )

    prompt_emb = embeddings[0]

    sims = util.cos_sim(
        prompt_emb,
        embeddings[1:]
    )[0]

    minilm_scores_dict = {
        op: sims[i].item()
        for i, op in enumerate(options)
    }

    minilm_top3 = sorted(
        minilm_scores_dict,
        key=minilm_scores_dict.get,
        reverse=True
    )[:3]

    minilm_predictions.append(minilm_top3)

    score = map3(
        row["answer"],
        minilm_top3
    )

    minilm_scores.append(score)

    #  Improvement Count 

    if (
        row["answer"] not in tfidf_top3
        and
        row["answer"] in minilm_top3
    ):
        improved_count += 1

In [246]:
minilm_map3 = np.mean(minilm_scores)

print("MiniLM MAP@3 =", minilm_map3)

print("Improvement Count =", improved_count)

MiniLM MAP@3 = 0.4230833333333333
Improvement Count = 502

#### Q11

In [247]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

In [248]:
prompt = tr[1]["prompt"]

candidate_labels = [
    tr[1]["A"],
    tr[1]["B"],
    tr[1]["C"]
]

In [250]:
result = classifier(
    prompt,
    candidate_labels
)

print(result)

{'sequence': 'What is accelerator-based light-ion fusion?', 'labels': ['Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.'], 'scores': [0.4574531018733978, 0.2750643193721771, 0.2674825191497803]}

In [251]:
print(result["labels"])
print(result["scores"])

['Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.']
[0.4574531018733978, 0.2750643193721771, 0.2674825191497803]

In [252]:
round(result["scores"][0], 4)

0.4575

#### Q12

In [253]:
result_multi = classifier(
    prompt,
    candidate_labels,
    multi_label=True
)

In [254]:
del sum

NameError: name 'sum' is not defined

In [255]:
softmax_sum = sum(result["scores"])

sigmoid_sum = sum(result_multi["scores"])

difference = abs(
    softmax_sum - sigmoid_sum
)

print(softmax_sum)
print(sigmoid_sum)
print(round(difference, 4))

0.9999999403953552
0.0005096085387776839
0.9995

In [256]:
print(result_multi)

{'sequence': 'What is accelerator-based light-ion fusion?', 'labels': ['Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.'], 'scores': [0.00046927202492952347, 2.063589454337489e-05, 1.9700619304785505e-05]}

In [259]:
print(result_multi["labels"])
print(result_multi["scores"])

['Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively easy to implement and can be done in an efficient manner, requiring only a vacuum tube, a pair of electrodes, and a high-voltage transformer. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce heavy-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 10 kV between the electrodes.', 'Accelerator-based light-ion fusion is a technique that uses particle accelerators to achieve particle kinetic energies sufficient to induce light-ion fusion reactions. This method is relatively difficult to implement and requires a complex system of vacuum tubes, electrodes, and transformers. Fusion can be observed with as little as 100 kV between the electrodes.']
[0.00046927202492952347, 2.063589454337489e-05, 1.9700619304785505e-05]

#### Q13

In [261]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

question = (
    f"Question: {tr[0]['prompt']}. "
    f"Is the correct answer A: {tr[0]['A']} "
    f"or B: {tr[0]['B']}? "
    f"Answer with just the letter A or B."
)

inputs = tokenizer(question, return_tensors="pt")

outputs = model.generate(
    **inputs,
    max_new_tokens=5
)

answer = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(answer)

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

B

In [262]:
import transformers
print(transformers.__version__)

5.0.0